name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_Yb56uRQnHLwonVjnaHKfZL7x
  VERCEL_PROJECT_ID: prj_rkqawygfkdAS5B9QY6wKGWVGvfUy
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=4ch1UE7IsOInkNj1BY43tXEV
      - name: Build Project Artifacts
        run: vercel build --token=4ch1UE7IsOInkNj1BY43tXEV
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=4ch1UE7IsOInkNj1BY43tXEV
